/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baug_demo_BaugDemo */

#ifndef _Included_com_baug_demo_BaugDemo
#define _Included_com_baug_demo_BaugDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baug_demo_BaugDemo
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_baug_demo_BaugDemo_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
